DEV:
    minCapacity: 1
    maxCapacity: 10
    instanceType: g4dn.xlarge
    #keyPairName: "DEV-OCT-SEOUL-EC2ECS"
STG:
    minCapacity: 2
    maxCapacity: 10
    instanceType: g4dn.xlarge
    #keyPairName: "STG-OCT-SEOUL-EC2ECS"